plugins {
    id("java")
}

group = providers.gradleProperty("project.group").get()
version = providers.gradleProperty("project.version").get()

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(libs.versions.java.get()))
    }
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs
            << "-parameters"
            << "-Xlint:unchecked"
            << "-Xlint:deprecation"
}

dependencies {
    compileOnly(libs.annotations)
}