plugins {
    id("jacoco")
    id("info.solidsoft.pitest")
}

jacoco {
    toolVersion = libs.versions.jacoco.get()
}

tasks.named("jacocoTestReport") {
    dependsOn(tasks.named("check"))

    reports {
        xml.required = true
        html.required = true
        csv.required = false
    }
}

pitest {
    junit5PluginVersion = libs.versions.pitest.junit.get()

    threads = 4

    outputFormats = ["HTML", "XML"]
    timestampedReports = false
}

tasks.register("coverageCheck") {
    group = "quality"
    dependsOn(tasks.named("jacocoTestReport"))
}

tasks.named("test") {
    finalizedBy(tasks.named("coverageCheck"))
}

tasks.register("mutationCheck") {
    group = "quality"
    dependsOn(tasks.named("pitest"))
}