plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenCentral()
    }
}

rootProject.name = "fair-share"

include(
        "app",
        "core:common",
        "core:quantity",
        "core:product",
        "core:pricing",
        "core:rules",
        "core:graphs"
)