package com.github.monaboiste.fairshare.settlement.domain;

public sealed interface SettlementRejection
        permits SettlementNotFound,
                ParticipantIdentifierConflict,
                ParticipantNotFound,
                EmptyShareAllocation,
                NonPositiveExpenseAmount,
                NonPositiveRepaymentAmount,
                RepaymentIdentifierConflict,
                RepaymentNotFound,
                RepaymentAlreadyCancelled,
                RepaymentCurrencyMismatch,
                RepaymentAmountPrecisionExceeded,
                SelfDirectedRepayment,
                ExpenseIdentifierConflict,
                ExpenseNotFound,
                ExpenseAlreadyCancelled,
                ParticipantReferenced,
                MissingExchangeRate,
                ExactShareCurrencyMismatch,
                NonPositiveExactShare,
                ExactShareSumMismatch,
                NonPositiveShareWeight,
                ExchangeRateTargetMismatch,
                ExplicitIdentityExchangeRate,
                ExchangeRateOverrideMismatch {}
